### ISSUE TITLE
Crash when tapping on a newly created deck.

### ISSUE THREAD

**Issue by cody-gh** [rh-id/a-flash-deck#16]
At the main screen, tap the menu button on the top left, then tap Decks. Tap the + button on the top right to create a new deck. Give it a name and tap save. Tap on the deck that you just created and the app will crash.

Version used was 1.7.3+43

**Comment by rh-id** [comment]
Thanks for the step by step report

**Comment by rh-id** [comment]
Fixed in 1.7.5+45
