### ISSUE TITLE
MCQ

### ISSUE THREAD

**Issue by ag6ag1** [rh-id/a-flash-deck#9]
feature request 

can we add an option for multiples choices?

Thank you.

**Comment by rh-id** [comment]
Hello, technically can be added, but it is not suitable feature for flash card app. Flash card typically simple, you see the question and then flip the card for short and precise answers.

This feature is more suitable for quizz app or questionnaire app where usually a more comprehensive questions and answers were made.

So, no this feature won't be added, thanks for the input.
